data <- read.table ("household_power_consumption.txt", sep= ";", na.strings = "?", nrows=3000, skip=66629)
names(data)<-c("Date","Time","Global_active_power","Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
realdata <- subset(data, Date=="1/2/2007"| Date =="2/2/2007")
datetime <- strptime(paste(realdata$Date, realdata$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
GAP <- as.numeric(realdata$Global_active_power)
plot(datetime, GAP,type="l",xlab="",ylab="Global Active Power")
dev.copy(png,filename="plot2.png",width=480,height=480,units="px")
dev.off()